Update test
akiosako/crud_sample pull request #9
Opened 2023-03-12 13:12 UTC by akiosako

お世話になっております。
最終課題の単体テストを行いました。
ハッシュコード：https://github.com/akiosako/crud_sample/commit/196d3c3141a2a2b571e32ac88fbbe5d41ae5daf3
■serviceImplのupdateMsg()が「指定されたidが存在するときメッセージが更新されること」をテスト
■テスト結果→成功
■updateMsgの処理の流れ
1. findByIdでidが存在することを確認
2. updateMsgで更新
3. 戻り値なし
という流れです。
voidメソッドのため、返ってきた結果を照合することが出来ず、消極的ですが「失敗していないこと」を確認した
形になったという感じだと思うのですが、この認識で正しいでしょうか。

2023-03-12 13:25 UTC, TomooAkamatsu commented on src/test/java/raisetech/crudsample/service/MsgServiceImplTest.java
> +    doNothing().when(msgMapper).updateMsg(1, "Hello");
ここから下は別のテストケースに分けてもいいと思います。

2023-03-12 13:26 UTC, yoshi-koyama requested changes

2023-03-12 13:26 UTC, yoshi-koyama commented on src/test/java/raisetech/crudsample/service/MsgServiceImplTest.java
> +  public void 指定されたidが存在する時メッセージが更新されること() {
存在しないときのテストはしないですか？

2023-03-12 13:26 UTC, yoshi-koyama commented on src/test/java/raisetech/crudsample/service/MsgServiceImplTest.java
> +      fail(e.getMessage());
こういうのいいですね！いいテストの書き方です。

2023-03-12 13:27 UTC, yoshi-koyama commented on src/test/java/raisetech/crudsample/service/MsgServiceImplTest.java
> +    assertThat(actual).isEqualTo(new Message(1, "Hello"));
更新のテスト、つまりupdateMsgメソッドのテストなのでこちらの記述は不要です。

2023-03-12 13:30 UTC, akiosako commented on src/test/java/raisetech/crudsample/service/MsgServiceImplTest.java
> +  public void 指定されたidが存在する時メッセージが更新されること() {
例外発生させるテストも実装致します！

2023-03-12 14:03 UTC, akiosako commented on src/test/java/raisetech/crudsample/service/MsgServiceImplTest.java
> +      fail(e.getMessage());
ありがとうございます・・！

2023-03-12 14:05 UTC, akiosako commented on src/test/java/raisetech/crudsample/service/MsgServiceImplTest.java
> +    assertThat(actual).isEqualTo(new Message(1, "Hello"));
表題のテスト以外のテストはしなくて良いのですね。findByIdは既に別個でテスト実装しているのもあり、記載について迷いましたが、納得しました。
findByIdのテストについては削除します。

2023-03-12 14:20 UTC, akiosako commented on src/test/java/raisetech/crudsample/service/MsgServiceImplTest.java
> +    doNothing().when(msgMapper).updateMsg(1, "Hello");
対応としては、findByIdのassertのテストをここでは行わずに削除、mapperが呼び出されているかどうかの確認だけ行うことにしました。
テストケースを分けることについて、わからなかったので、また質問させて下さい。

2023-03-13 11:57 UTC, TomooAkamatsu commented on src/test/java/raisetech/crudsample/service/MsgServiceImplTest.java
> +    doThrow(new ResourceNotFoundException("resource not found")).when(msgMapper).findById(999);
MapperクラスからResourceNotFoundExceptionが投げられるわけではないですね。
(結果的にテストは通ると思いますが...)

このケースの場合、nullを内包しているOptionalがMapperから帰ってきた時にServiceクラスで適切に例外が投げられることを確かめたいです！

2023-03-13 12:32 UTC, akiosako commented on src/test/java/raisetech/crudsample/service/MsgServiceImplTest.java
> +    doThrow(new ResourceNotFoundException("resource not found")).when(msgMapper).findById(999);
確かにmapperが例外を返しているのは変です・・・！！
ご指摘ありがとうございます！

2023-03-13 12:42 UTC, TomooAkamatsu commented on src/test/java/raisetech/crudsample/service/MsgServiceImplTest.java
> +    try {
結局ここのtry-catchでは何も検証されていないように見えます。
fail()が必要じゃないですか？

2023-03-13 12:45 UTC, TomooAkamatsu commented on src/test/java/raisetech/crudsample/service/MsgServiceImplTest.java
> +    verify(msgMapper).findById(999);
ここも何回呼ばれたか確かめておくといいかもです。

2023-03-13 12:55 UTC, akiosako commented on src/test/java/raisetech/crudsample/service/MsgServiceImplTest.java
> +    try {
fail()が呼ばれないので成功とする感じでどうでしょうか！

2023-03-13 13:05 UTC, TomooAkamatsu commented on src/test/java/raisetech/crudsample/service/MsgServiceImplTest.java
> +    try {
failの行に到達すると失敗するという認識でOKです。
なので、今回の場合はその場所で問題ないと思います。

2023-03-13 13:05 UTC, TomooAkamatsu commented on src/test/java/raisetech/crudsample/service/MsgServiceImplTest.java
> +    try {
試しにcatch側に書くとテスト失敗すると思いますが。。

2023-03-13 13:08 UTC, TomooAkamatsu commented on src/test/java/raisetech/crudsample/service/MsgServiceImplTest.java
> +    try {
ただ、正確になんのクラスの例外かまでは追えていないので、書き方変更した方がいいかもですね。
classを指定して例外が投げられたことを確認できる方法があるので調べてみてください。

例えば、現状だと`ResourceNotFoundException`以外の例外が出た場合もテストOKとなると思います。(その場合はcatchもされずスルーされる)

2023-03-13 13:31 UTC, TomooAkamatsu approved these changes
LGTMです！

2023-03-13 13:36 UTC, merged